### PR TITLE
Some gradle updates

### PR DESCRIPTION
**Pull request by dbachelder**
updated some dependencies
added gradle wrapper
project is now multi-module

### CODE REVIEW

**Comment by dbachelder** [comment]
With these changes the project now correctly imports and runs in Android Studio... should also continue to work in Eclipse.. Although I'm not sure why you would want to ;)

**Comment by dbachelder** [comment]
@evyatar-via @mr-ken do you guys want pull requests on this project?

**Comment by evyatar-via** [comment]
Thanks, but we're good.

**Comment by dbachelder** [comment]
fair enough.

**Pull request closed without merging**
